// Code generated by xgen. DO NOT EDIT.

use serde::{Deserialize, Serialize};


// AdministrationProprietaryMessageV02 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct AdministrationProprietaryMessageV02 {
	#[serde(rename = "MsgId")]
	pub msg_id: Option<MessageReference>,
	#[serde(rename = "Rltd")]
	pub rltd: Option<MessageReference>,
	#[serde(rename = "Prvs")]
	pub prvs: Option<MessageReference>,
	#[serde(rename = "Othr")]
	pub othr: Option<MessageReference>,
	#[serde(rename = "PrtryData")]
	pub prtry_data: ProprietaryData5,
}


// Max35Text ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Max35Text {
	#[serde(rename = "Max35Text")]
	pub max35_text: String,
}


// MessageReference ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct MessageReference {
	#[serde(rename = "Ref")]
	pub ref_attr: String,
}


// ProprietaryData5 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ProprietaryData5 {
	#[serde(rename = "Tp")]
	pub tp: String,
	#[serde(rename = "Data")]
	pub data: SupplementaryDataEnvelope1,
}


// SupplementaryDataEnvelope1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct SupplementaryDataEnvelope1 {
}
