// Code generated by xgen. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use crate::Document;


// document ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct document {
	#[serde(rename = "Document")]
	pub document: Document,
}


// ISODateTime ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ISODateTime {
	#[serde(rename = "ISODateTime")]
	pub iso_date_time: String,
}


// Max20000Text ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Max20000Text {
	#[serde(rename = "Max20000Text")]
	pub max20000_text: String,
}


// Max350Text ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Max350Text {
	#[serde(rename = "Max350Text")]
	pub max350_text: String,
}


// Max35Text ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Max35Text {
	#[serde(rename = "Max35Text")]
	pub max35_text: String,
}


// MessageReference ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct MessageReference {
	#[serde(rename = "Ref")]
	pub ref_attr: String,
}


// RejectionReason2 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct RejectionReason2 {
	#[serde(rename = "RjctgPtyRsn")]
	pub rjctg_pty_rsn: String,
	#[serde(rename = "RjctnDtTm")]
	pub rjctn_dt_tm: Option<String>,
	#[serde(rename = "ErrLctn")]
	pub err_lctn: Option<String>,
	#[serde(rename = "RsnDesc")]
	pub rsn_desc: Option<String>,
	#[serde(rename = "AddtlData")]
	pub addtl_data: Option<String>,
}


// Admi00200101 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Admi00200101 {
	#[serde(rename = "RltdRef")]
	pub rltd_ref: MessageReference,
	#[serde(rename = "Rsn")]
	pub rsn: RejectionReason2,
}
