// Code generated by xgen. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use crate::Document;


// document ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct document {
	#[serde(rename = "Document")]
	pub document: Document,
}


// AccountIdentification4Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct AccountIdentification4Choice {
	#[serde(rename = "IBAN")]
	pub iban: Option<String>,
	#[serde(rename = "Othr")]
	pub othr: Option<GenericAccountIdentification1>,
}


// AccountInterest4 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct AccountInterest4 {
	#[serde(rename = "Tp")]
	pub tp: InterestType1Choice,
	#[serde(rename = "Rate")]
	pub rate: Vec<Rate4>,
	#[serde(rename = "FrToDt")]
	pub fr_to_dt: DateTimePeriod1,
	#[serde(rename = "Rsn")]
	pub rsn: String,
	#[serde(rename = "Tax")]
	pub tax: TaxCharges2,
}


// AccountNotification17 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct AccountNotification17 {
	#[serde(rename = "Id")]
	pub id: String,
	#[serde(rename = "NtfctnPgntn")]
	pub ntfctn_pgntn: Pagination1,
	#[serde(rename = "ElctrncSeqNb")]
	pub elctrnc_seq_nb: f64,
	#[serde(rename = "RptgSeq")]
	pub rptg_seq: SequenceRange1Choice,
	#[serde(rename = "LglSeqNb")]
	pub lgl_seq_nb: f64,
	#[serde(rename = "CreDtTm")]
	pub cre_dt_tm: String,
	#[serde(rename = "FrToDt")]
	pub fr_to_dt: DateTimePeriod1,
	#[serde(rename = "CpyDplctInd")]
	pub cpy_dplct_ind: String,
	#[serde(rename = "RptgSrc")]
	pub rptg_src: ReportingSource1Choice,
	#[serde(rename = "Acct")]
	pub acct: CashAccount39,
	#[serde(rename = "RltdAcct")]
	pub rltd_acct: CashAccount38,
	#[serde(rename = "Intrst")]
	pub intrst: Vec<AccountInterest4>,
	#[serde(rename = "TxsSummry")]
	pub txs_summry: TotalTransactions6,
	#[serde(rename = "Ntry")]
	pub ntry: Vec<ReportEntry10>,
	#[serde(rename = "AddtlNtfctnInf")]
	pub addtl_ntfctn_inf: String,
}


// AccountSchemeName1Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct AccountSchemeName1Choice {
	#[serde(rename = "Cd")]
	pub cd: Option<String>,
	#[serde(rename = "Prtry")]
	pub prtry: Option<String>,
}


// ActiveCurrencyAndAmountSimpleType ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ActiveCurrencyAndAmountSimpleType {
	#[serde(rename = "ActiveCurrencyAndAmount_SimpleType")]
	pub active_currency_and_amount_simple_type: f64,
}


// ActiveCurrencyAndAmount ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ActiveCurrencyAndAmount {
	#[serde(rename = "Ccy")]
	pub ccy: String,
	#[serde(rename = "$value")]
	pub value: f64,
}


// ActiveCurrencyCode ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ActiveCurrencyCode {
	#[serde(rename = "ActiveCurrencyCode")]
	pub active_currency_code: String,
}


// ActiveOrHistoricCurrencyAnd13DecimalAmountSimpleType ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ActiveOrHistoricCurrencyAnd13DecimalAmountSimpleType {
	#[serde(rename = "ActiveOrHistoricCurrencyAnd13DecimalAmount_SimpleType")]
	pub active_or_historic_currency_and13_decimal_amount_simple_type: f64,
}


// ActiveOrHistoricCurrencyAnd13DecimalAmount ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ActiveOrHistoricCurrencyAnd13DecimalAmount {
	#[serde(rename = "Ccy")]
	pub ccy: String,
	#[serde(rename = "$value")]
	pub value: f64,
}


// ActiveOrHistoricCurrencyAndAmountSimpleType ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ActiveOrHistoricCurrencyAndAmountSimpleType {
	#[serde(rename = "ActiveOrHistoricCurrencyAndAmount_SimpleType")]
	pub active_or_historic_currency_and_amount_simple_type: f64,
}


// ActiveOrHistoricCurrencyAndAmount ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ActiveOrHistoricCurrencyAndAmount {
	#[serde(rename = "Ccy")]
	pub ccy: String,
	#[serde(rename = "$value")]
	pub value: f64,
}


// ActiveOrHistoricCurrencyAndAmountRange2 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ActiveOrHistoricCurrencyAndAmountRange2 {
	#[serde(rename = "Amt")]
	pub amt: ImpliedCurrencyAmountRange1Choice,
	#[serde(rename = "CdtDbtInd")]
	pub cdt_dbt_ind: String,
	#[serde(rename = "Ccy")]
	pub ccy: String,
}


// ActiveOrHistoricCurrencyCode ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ActiveOrHistoricCurrencyCode {
	#[serde(rename = "ActiveOrHistoricCurrencyCode")]
	pub active_or_historic_currency_code: String,
}


// AddressType2Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct AddressType2Code {
	#[serde(rename = "AddressType2Code")]
	pub address_type2_code: String,
}


// AddressType3Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct AddressType3Choice {
	#[serde(rename = "Cd")]
	pub cd: Option<String>,
	#[serde(rename = "Prtry")]
	pub prtry: Option<GenericIdentification30>,
}


// AmountAndCurrencyExchange3 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct AmountAndCurrencyExchange3 {
	#[serde(rename = "InstdAmt")]
	pub instd_amt: AmountAndCurrencyExchangeDetails3,
	#[serde(rename = "TxAmt")]
	pub tx_amt: AmountAndCurrencyExchangeDetails3,
	#[serde(rename = "CntrValAmt")]
	pub cntr_val_amt: AmountAndCurrencyExchangeDetails3,
	#[serde(rename = "AnncdPstngAmt")]
	pub anncd_pstng_amt: AmountAndCurrencyExchangeDetails3,
	#[serde(rename = "PrtryAmt")]
	pub prtry_amt: Vec<AmountAndCurrencyExchangeDetails4>,
}


// AmountAndCurrencyExchangeDetails3 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct AmountAndCurrencyExchangeDetails3 {
	#[serde(rename = "Amt")]
	pub amt: ActiveOrHistoricCurrencyAndAmount,
	#[serde(rename = "CcyXchg")]
	pub ccy_xchg: CurrencyExchange5,
}


// AmountAndCurrencyExchangeDetails4 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct AmountAndCurrencyExchangeDetails4 {
	#[serde(rename = "Tp")]
	pub tp: String,
	#[serde(rename = "Amt")]
	pub amt: ActiveOrHistoricCurrencyAndAmount,
	#[serde(rename = "CcyXchg")]
	pub ccy_xchg: CurrencyExchange5,
}


// AmountAndDirection35 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct AmountAndDirection35 {
	#[serde(rename = "Amt")]
	pub amt: f64,
	#[serde(rename = "CdtDbtInd")]
	pub cdt_dbt_ind: String,
}


// AmountRangeBoundary1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct AmountRangeBoundary1 {
	#[serde(rename = "BdryAmt")]
	pub bdry_amt: f64,
	#[serde(rename = "Incl")]
	pub incl: bool,
}


// AnyBICDec2014Identifier ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct AnyBICDec2014Identifier {
	#[serde(rename = "AnyBICDec2014Identifier")]
	pub any_bic_dec2014_identifier: String,
}


// AttendanceContext1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct AttendanceContext1Code {
	#[serde(rename = "AttendanceContext1Code")]
	pub attendance_context1_code: String,
}


// AuthenticationEntity1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct AuthenticationEntity1Code {
	#[serde(rename = "AuthenticationEntity1Code")]
	pub authentication_entity1_code: String,
}


// AuthenticationMethod1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct AuthenticationMethod1Code {
	#[serde(rename = "AuthenticationMethod1Code")]
	pub authentication_method1_code: String,
}


// BICFIDec2014Identifier ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct BICFIDec2014Identifier {
	#[serde(rename = "BICFIDec2014Identifier")]
	pub bicfi_dec2014_identifier: String,
}


// BankToCustomerDebitCreditNotificationV08 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct BankToCustomerDebitCreditNotificationV08 {
	#[serde(rename = "GrpHdr")]
	pub grp_hdr: GroupHeader81,
	#[serde(rename = "Ntfctn")]
	pub ntfctn: Vec<AccountNotification17>,
	#[serde(rename = "SplmtryData")]
	pub splmtry_data: Vec<SupplementaryData1>,
}


// BankTransactionCodeStructure4 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct BankTransactionCodeStructure4 {
	#[serde(rename = "Domn")]
	pub domn: BankTransactionCodeStructure5,
	#[serde(rename = "Prtry")]
	pub prtry: ProprietaryBankTransactionCodeStructure1,
}


// BankTransactionCodeStructure5 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct BankTransactionCodeStructure5 {
	#[serde(rename = "Cd")]
	pub cd: String,
	#[serde(rename = "Fmly")]
	pub fmly: BankTransactionCodeStructure6,
}


// BankTransactionCodeStructure6 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct BankTransactionCodeStructure6 {
	#[serde(rename = "Cd")]
	pub cd: String,
	#[serde(rename = "SubFmlyCd")]
	pub sub_fmly_cd: String,
}


// BaseOneRate ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct BaseOneRate {
	#[serde(rename = "BaseOneRate")]
	pub base_one_rate: f64,
}


// BatchInformation2 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct BatchInformation2 {
	#[serde(rename = "MsgId")]
	pub msg_id: String,
	#[serde(rename = "PmtInfId")]
	pub pmt_inf_id: String,
	#[serde(rename = "NbOfTxs")]
	pub nb_of_txs: String,
	#[serde(rename = "TtlAmt")]
	pub ttl_amt: ActiveOrHistoricCurrencyAndAmount,
	#[serde(rename = "CdtDbtInd")]
	pub cdt_dbt_ind: String,
}


// BranchAndFinancialInstitutionIdentification6 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct BranchAndFinancialInstitutionIdentification6 {
	#[serde(rename = "FinInstnId")]
	pub fin_instn_id: FinancialInstitutionIdentification18,
	#[serde(rename = "BrnchId")]
	pub brnch_id: BranchData3,
}


// BranchData3 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct BranchData3 {
	#[serde(rename = "Id")]
	pub id: String,
	#[serde(rename = "LEI")]
	pub lei: String,
	#[serde(rename = "Nm")]
	pub nm: String,
	#[serde(rename = "PstlAdr")]
	pub pstl_adr: PostalAddress24,
}


// CSCManagement1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CSCManagement1Code {
	#[serde(rename = "CSCManagement1Code")]
	pub csc_management1_code: String,
}


// CardAggregated2 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CardAggregated2 {
	#[serde(rename = "AddtlSvc")]
	pub addtl_svc: String,
	#[serde(rename = "TxCtgy")]
	pub tx_ctgy: String,
	#[serde(rename = "SaleRcncltnId")]
	pub sale_rcncltn_id: String,
	#[serde(rename = "SeqNbRg")]
	pub seq_nb_rg: CardSequenceNumberRange1,
	#[serde(rename = "TxDtRg")]
	pub tx_dt_rg: DateOrDateTimePeriod1Choice,
}


// CardDataReading1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CardDataReading1Code {
	#[serde(rename = "CardDataReading1Code")]
	pub card_data_reading1_code: String,
}


// CardEntry4 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CardEntry4 {
	#[serde(rename = "Card")]
	pub card: PaymentCard4,
	#[serde(rename = "POI")]
	pub poi: PointOfInteraction1,
	#[serde(rename = "AggtdNtry")]
	pub aggtd_ntry: CardAggregated2,
	#[serde(rename = "PrePdAcct")]
	pub pre_pd_acct: CashAccount38,
}


// CardIndividualTransaction2 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CardIndividualTransaction2 {
	#[serde(rename = "ICCRltdData")]
	pub icc_rltd_data: String,
	#[serde(rename = "PmtCntxt")]
	pub pmt_cntxt: PaymentContext3,
	#[serde(rename = "AddtlSvc")]
	pub addtl_svc: String,
	#[serde(rename = "TxCtgy")]
	pub tx_ctgy: String,
	#[serde(rename = "SaleRcncltnId")]
	pub sale_rcncltn_id: String,
	#[serde(rename = "SaleRefNb")]
	pub sale_ref_nb: String,
	#[serde(rename = "RePresntmntRsn")]
	pub re_presntmnt_rsn: String,
	#[serde(rename = "SeqNb")]
	pub seq_nb: String,
	#[serde(rename = "TxId")]
	pub tx_id: TransactionIdentifier1,
	#[serde(rename = "Pdct")]
	pub pdct: Product2,
	#[serde(rename = "VldtnDt")]
	pub vldtn_dt: String,
	#[serde(rename = "VldtnSeqNb")]
	pub vldtn_seq_nb: String,
}


// CardPaymentServiceType2Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CardPaymentServiceType2Code {
	#[serde(rename = "CardPaymentServiceType2Code")]
	pub card_payment_service_type2_code: String,
}


// CardSecurityInformation1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CardSecurityInformation1 {
	#[serde(rename = "CSCMgmt")]
	pub csc_mgmt: String,
	#[serde(rename = "CSCVal")]
	pub csc_val: String,
}


// CardSequenceNumberRange1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CardSequenceNumberRange1 {
	#[serde(rename = "FrstTx")]
	pub frst_tx: String,
	#[serde(rename = "LastTx")]
	pub last_tx: String,
}


// CardTransaction17 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CardTransaction17 {
	#[serde(rename = "Card")]
	pub card: PaymentCard4,
	#[serde(rename = "POI")]
	pub poi: PointOfInteraction1,
	#[serde(rename = "Tx")]
	pub tx: CardTransaction3Choice,
	#[serde(rename = "PrePdAcct")]
	pub pre_pd_acct: CashAccount38,
}


// CardTransaction3Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CardTransaction3Choice {
	#[serde(rename = "Aggtd")]
	pub aggtd: Option<CardAggregated2>,
	#[serde(rename = "Indv")]
	pub indv: Option<CardIndividualTransaction2>,
}


// CardholderAuthentication2 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CardholderAuthentication2 {
	#[serde(rename = "AuthntcnMtd")]
	pub authntcn_mtd: String,
	#[serde(rename = "AuthntcnNtty")]
	pub authntcn_ntty: String,
}


// CardholderVerificationCapability1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CardholderVerificationCapability1Code {
	#[serde(rename = "CardholderVerificationCapability1Code")]
	pub cardholder_verification_capability1_code: String,
}


// CashAccount38 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CashAccount38 {
	#[serde(rename = "Id")]
	pub id: AccountIdentification4Choice,
	#[serde(rename = "Tp")]
	pub tp: CashAccountType2Choice,
	#[serde(rename = "Ccy")]
	pub ccy: String,
	#[serde(rename = "Nm")]
	pub nm: String,
	#[serde(rename = "Prxy")]
	pub prxy: ProxyAccountIdentification1,
}


// CashAccount39 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CashAccount39 {
	#[serde(rename = "Id")]
	pub id: AccountIdentification4Choice,
	#[serde(rename = "Tp")]
	pub tp: CashAccountType2Choice,
	#[serde(rename = "Ccy")]
	pub ccy: String,
	#[serde(rename = "Nm")]
	pub nm: String,
	#[serde(rename = "Prxy")]
	pub prxy: ProxyAccountIdentification1,
	#[serde(rename = "Ownr")]
	pub ownr: PartyIdentification135,
	#[serde(rename = "Svcr")]
	pub svcr: BranchAndFinancialInstitutionIdentification6,
}


// CashAccountType2Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CashAccountType2Choice {
	#[serde(rename = "Cd")]
	pub cd: Option<String>,
	#[serde(rename = "Prtry")]
	pub prtry: Option<String>,
}


// CashAvailability1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CashAvailability1 {
	#[serde(rename = "Dt")]
	pub dt: CashAvailabilityDate1Choice,
	#[serde(rename = "Amt")]
	pub amt: ActiveOrHistoricCurrencyAndAmount,
	#[serde(rename = "CdtDbtInd")]
	pub cdt_dbt_ind: String,
}


// CashAvailabilityDate1Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CashAvailabilityDate1Choice {
	#[serde(rename = "NbOfDays")]
	pub nb_of_days: Option<String>,
	#[serde(rename = "ActlDt")]
	pub actl_dt: Option<String>,
}


// CashDeposit1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CashDeposit1 {
	#[serde(rename = "NoteDnmtn")]
	pub note_dnmtn: ActiveCurrencyAndAmount,
	#[serde(rename = "NbOfNotes")]
	pub nb_of_notes: String,
	#[serde(rename = "Amt")]
	pub amt: ActiveCurrencyAndAmount,
}


// ChargeBearerType1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ChargeBearerType1Code {
	#[serde(rename = "ChargeBearerType1Code")]
	pub charge_bearer_type1_code: String,
}


// ChargeIncludedIndicator ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ChargeIncludedIndicator {
	#[serde(rename = "ChargeIncludedIndicator")]
	pub charge_included_indicator: bool,
}


// ChargeType3Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ChargeType3Choice {
	#[serde(rename = "Cd")]
	pub cd: Option<String>,
	#[serde(rename = "Prtry")]
	pub prtry: Option<GenericIdentification3>,
}


// Charges6 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Charges6 {
	#[serde(rename = "TtlChrgsAndTaxAmt")]
	pub ttl_chrgs_and_tax_amt: ActiveOrHistoricCurrencyAndAmount,
	#[serde(rename = "Rcrd")]
	pub rcrd: Vec<ChargesRecord3>,
}


// ChargesRecord3 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ChargesRecord3 {
	#[serde(rename = "Amt")]
	pub amt: ActiveOrHistoricCurrencyAndAmount,
	#[serde(rename = "CdtDbtInd")]
	pub cdt_dbt_ind: String,
	#[serde(rename = "ChrgInclInd")]
	pub chrg_incl_ind: bool,
	#[serde(rename = "Tp")]
	pub tp: ChargeType3Choice,
	#[serde(rename = "Rate")]
	pub rate: f64,
	#[serde(rename = "Br")]
	pub br: String,
	#[serde(rename = "Agt")]
	pub agt: BranchAndFinancialInstitutionIdentification6,
	#[serde(rename = "Tax")]
	pub tax: TaxCharges2,
}


// ClearingSystemIdentification2Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ClearingSystemIdentification2Choice {
	#[serde(rename = "Cd")]
	pub cd: Option<String>,
	#[serde(rename = "Prtry")]
	pub prtry: Option<String>,
}


// ClearingSystemMemberIdentification2 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ClearingSystemMemberIdentification2 {
	#[serde(rename = "ClrSysId")]
	pub clr_sys_id: ClearingSystemIdentification2Choice,
	#[serde(rename = "MmbId")]
	pub mmb_id: String,
}


// Contact4 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Contact4 {
	#[serde(rename = "NmPrfx")]
	pub nm_prfx: String,
	#[serde(rename = "Nm")]
	pub nm: String,
	#[serde(rename = "PhneNb")]
	pub phne_nb: String,
	#[serde(rename = "MobNb")]
	pub mob_nb: String,
	#[serde(rename = "FaxNb")]
	pub fax_nb: String,
	#[serde(rename = "EmailAdr")]
	pub email_adr: String,
	#[serde(rename = "EmailPurp")]
	pub email_purp: String,
	#[serde(rename = "JobTitl")]
	pub job_titl: String,
	#[serde(rename = "Rspnsblty")]
	pub rspnsblty: String,
	#[serde(rename = "Dept")]
	pub dept: String,
	#[serde(rename = "Othr")]
	pub othr: Vec<OtherContact1>,
	#[serde(rename = "PrefrdMtd")]
	pub prefrd_mtd: String,
}


// CopyDuplicate1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CopyDuplicate1Code {
	#[serde(rename = "CopyDuplicate1Code")]
	pub copy_duplicate1_code: String,
}


// CorporateAction9 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CorporateAction9 {
	#[serde(rename = "EvtTp")]
	pub evt_tp: String,
	#[serde(rename = "EvtId")]
	pub evt_id: String,
}


// CountryCode ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CountryCode {
	#[serde(rename = "CountryCode")]
	pub country_code: String,
}


// CreditDebitCode ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CreditDebitCode {
	#[serde(rename = "CreditDebitCode")]
	pub credit_debit_code: String,
}


// CreditorReferenceInformation2 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CreditorReferenceInformation2 {
	#[serde(rename = "Tp")]
	pub tp: CreditorReferenceType2,
	#[serde(rename = "Ref")]
	pub ref_attr: String,
}


// CreditorReferenceType1Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CreditorReferenceType1Choice {
	#[serde(rename = "Cd")]
	pub cd: Option<String>,
	#[serde(rename = "Prtry")]
	pub prtry: Option<String>,
}


// CreditorReferenceType2 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CreditorReferenceType2 {
	#[serde(rename = "CdOrPrtry")]
	pub cd_or_prtry: CreditorReferenceType1Choice,
	#[serde(rename = "Issr")]
	pub issr: String,
}


// CurrencyExchange5 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct CurrencyExchange5 {
	#[serde(rename = "SrcCcy")]
	pub src_ccy: String,
	#[serde(rename = "TrgtCcy")]
	pub trgt_ccy: String,
	#[serde(rename = "UnitCcy")]
	pub unit_ccy: String,
	#[serde(rename = "XchgRate")]
	pub xchg_rate: f64,
	#[serde(rename = "CtrctId")]
	pub ctrct_id: String,
	#[serde(rename = "QtnDt")]
	pub qtn_dt: String,
}


// DateAndDateTime2Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct DateAndDateTime2Choice {
	#[serde(rename = "Dt")]
	pub dt: Option<String>,
	#[serde(rename = "DtTm")]
	pub dt_tm: Option<String>,
}


// DateAndPlaceOfBirth1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct DateAndPlaceOfBirth1 {
	#[serde(rename = "BirthDt")]
	pub birth_dt: String,
	#[serde(rename = "PrvcOfBirth")]
	pub prvc_of_birth: String,
	#[serde(rename = "CityOfBirth")]
	pub city_of_birth: String,
	#[serde(rename = "CtryOfBirth")]
	pub ctry_of_birth: String,
}


// DateOrDateTimePeriod1Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct DateOrDateTimePeriod1Choice {
	#[serde(rename = "Dt")]
	pub dt: Option<DatePeriod2>,
	#[serde(rename = "DtTm")]
	pub dt_tm: Option<DateTimePeriod1>,
}


// DatePeriod2 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct DatePeriod2 {
	#[serde(rename = "FrDt")]
	pub fr_dt: String,
	#[serde(rename = "ToDt")]
	pub to_dt: String,
}


// DateTimePeriod1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct DateTimePeriod1 {
	#[serde(rename = "FrDtTm")]
	pub fr_dt_tm: String,
	#[serde(rename = "ToDtTm")]
	pub to_dt_tm: String,
}


// DecimalNumber ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct DecimalNumber {
	#[serde(rename = "DecimalNumber")]
	pub decimal_number: f64,
}


// DiscountAmountAndType1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct DiscountAmountAndType1 {
	#[serde(rename = "Tp")]
	pub tp: DiscountAmountType1Choice,
	#[serde(rename = "Amt")]
	pub amt: ActiveOrHistoricCurrencyAndAmount,
}


// DiscountAmountType1Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct DiscountAmountType1Choice {
	#[serde(rename = "Cd")]
	pub cd: Option<String>,
	#[serde(rename = "Prtry")]
	pub prtry: Option<String>,
}


// DisplayCapabilities1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct DisplayCapabilities1 {
	#[serde(rename = "DispTp")]
	pub disp_tp: String,
	#[serde(rename = "NbOfLines")]
	pub nb_of_lines: String,
	#[serde(rename = "LineWidth")]
	pub line_width: String,
}


// DocumentAdjustment1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct DocumentAdjustment1 {
	#[serde(rename = "Amt")]
	pub amt: ActiveOrHistoricCurrencyAndAmount,
	#[serde(rename = "CdtDbtInd")]
	pub cdt_dbt_ind: String,
	#[serde(rename = "Rsn")]
	pub rsn: String,
	#[serde(rename = "AddtlInf")]
	pub addtl_inf: String,
}


// DocumentLineIdentification1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct DocumentLineIdentification1 {
	#[serde(rename = "Tp")]
	pub tp: DocumentLineType1,
	#[serde(rename = "Nb")]
	pub nb: String,
	#[serde(rename = "RltdDt")]
	pub rltd_dt: String,
}


// DocumentLineInformation1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct DocumentLineInformation1 {
	#[serde(rename = "Id")]
	pub id: Vec<DocumentLineIdentification1>,
	#[serde(rename = "Desc")]
	pub desc: String,
	#[serde(rename = "Amt")]
	pub amt: RemittanceAmount3,
}


// DocumentLineType1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct DocumentLineType1 {
	#[serde(rename = "CdOrPrtry")]
	pub cd_or_prtry: DocumentLineType1Choice,
	#[serde(rename = "Issr")]
	pub issr: String,
}


// DocumentLineType1Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct DocumentLineType1Choice {
	#[serde(rename = "Cd")]
	pub cd: Option<String>,
	#[serde(rename = "Prtry")]
	pub prtry: Option<String>,
}


// DocumentType3Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct DocumentType3Code {
	#[serde(rename = "DocumentType3Code")]
	pub document_type3_code: String,
}


// DocumentType6Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct DocumentType6Code {
	#[serde(rename = "DocumentType6Code")]
	pub document_type6_code: String,
}


// EntryDetails9 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct EntryDetails9 {
	#[serde(rename = "Btch")]
	pub btch: BatchInformation2,
	#[serde(rename = "TxDtls")]
	pub tx_dtls: Vec<EntryTransaction10>,
}


// EntryStatus1Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct EntryStatus1Choice {
	#[serde(rename = "Cd")]
	pub cd: Option<String>,
	#[serde(rename = "Prtry")]
	pub prtry: Option<String>,
}


// EntryTransaction10 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct EntryTransaction10 {
	#[serde(rename = "Refs")]
	pub refs: TransactionReferences6,
	#[serde(rename = "Amt")]
	pub amt: ActiveOrHistoricCurrencyAndAmount,
	#[serde(rename = "CdtDbtInd")]
	pub cdt_dbt_ind: String,
	#[serde(rename = "AmtDtls")]
	pub amt_dtls: AmountAndCurrencyExchange3,
	#[serde(rename = "Avlbty")]
	pub avlbty: Vec<CashAvailability1>,
	#[serde(rename = "BkTxCd")]
	pub bk_tx_cd: BankTransactionCodeStructure4,
	#[serde(rename = "Chrgs")]
	pub chrgs: Charges6,
	#[serde(rename = "Intrst")]
	pub intrst: TransactionInterest4,
	#[serde(rename = "RltdPties")]
	pub rltd_pties: TransactionParties6,
	#[serde(rename = "RltdAgts")]
	pub rltd_agts: TransactionAgents5,
	#[serde(rename = "LclInstrm")]
	pub lcl_instrm: LocalInstrument2Choice,
	#[serde(rename = "Purp")]
	pub purp: Purpose2Choice,
	#[serde(rename = "RltdRmtInf")]
	pub rltd_rmt_inf: Vec<RemittanceLocation7>,
	#[serde(rename = "RmtInf")]
	pub rmt_inf: RemittanceInformation16,
	#[serde(rename = "RltdDts")]
	pub rltd_dts: TransactionDates3,
	#[serde(rename = "RltdPric")]
	pub rltd_pric: TransactionPrice4Choice,
	#[serde(rename = "RltdQties")]
	pub rltd_qties: Vec<TransactionQuantities3Choice>,
	#[serde(rename = "FinInstrmId")]
	pub fin_instrm_id: SecurityIdentification19,
	#[serde(rename = "Tax")]
	pub tax: TaxInformation8,
	#[serde(rename = "RtrInf")]
	pub rtr_inf: PaymentReturnReason5,
	#[serde(rename = "CorpActn")]
	pub corp_actn: CorporateAction9,
	#[serde(rename = "SfkpgAcct")]
	pub sfkpg_acct: SecuritiesAccount19,
	#[serde(rename = "CshDpst")]
	pub csh_dpst: Vec<CashDeposit1>,
	#[serde(rename = "CardTx")]
	pub card_tx: CardTransaction17,
	#[serde(rename = "AddtlTxInf")]
	pub addtl_tx_inf: String,
	#[serde(rename = "SplmtryData")]
	pub splmtry_data: Vec<SupplementaryData1>,
}


// Exact1NumericText ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Exact1NumericText {
	#[serde(rename = "Exact1NumericText")]
	pub exact1_numeric_text: String,
}


// Exact3NumericText ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Exact3NumericText {
	#[serde(rename = "Exact3NumericText")]
	pub exact3_numeric_text: String,
}


// Exact4AlphaNumericText ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Exact4AlphaNumericText {
	#[serde(rename = "Exact4AlphaNumericText")]
	pub exact4_alpha_numeric_text: String,
}


// ExternalAccountIdentification1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ExternalAccountIdentification1Code {
	#[serde(rename = "ExternalAccountIdentification1Code")]
	pub external_account_identification1_code: String,
}


// ExternalBankTransactionDomain1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ExternalBankTransactionDomain1Code {
	#[serde(rename = "ExternalBankTransactionDomain1Code")]
	pub external_bank_transaction_domain1_code: String,
}


// ExternalBankTransactionFamily1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ExternalBankTransactionFamily1Code {
	#[serde(rename = "ExternalBankTransactionFamily1Code")]
	pub external_bank_transaction_family1_code: String,
}


// ExternalBankTransactionSubFamily1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ExternalBankTransactionSubFamily1Code {
	#[serde(rename = "ExternalBankTransactionSubFamily1Code")]
	pub external_bank_transaction_sub_family1_code: String,
}


// ExternalCardTransactionCategory1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ExternalCardTransactionCategory1Code {
	#[serde(rename = "ExternalCardTransactionCategory1Code")]
	pub external_card_transaction_category1_code: String,
}


// ExternalCashAccountType1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ExternalCashAccountType1Code {
	#[serde(rename = "ExternalCashAccountType1Code")]
	pub external_cash_account_type1_code: String,
}


// ExternalChargeType1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ExternalChargeType1Code {
	#[serde(rename = "ExternalChargeType1Code")]
	pub external_charge_type1_code: String,
}


// ExternalClearingSystemIdentification1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ExternalClearingSystemIdentification1Code {
	#[serde(rename = "ExternalClearingSystemIdentification1Code")]
	pub external_clearing_system_identification1_code: String,
}


// ExternalDiscountAmountType1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ExternalDiscountAmountType1Code {
	#[serde(rename = "ExternalDiscountAmountType1Code")]
	pub external_discount_amount_type1_code: String,
}


// ExternalDocumentLineType1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ExternalDocumentLineType1Code {
	#[serde(rename = "ExternalDocumentLineType1Code")]
	pub external_document_line_type1_code: String,
}


// ExternalEntryStatus1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ExternalEntryStatus1Code {
	#[serde(rename = "ExternalEntryStatus1Code")]
	pub external_entry_status1_code: String,
}


// ExternalFinancialInstitutionIdentification1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ExternalFinancialInstitutionIdentification1Code {
	#[serde(rename = "ExternalFinancialInstitutionIdentification1Code")]
	pub external_financial_institution_identification1_code: String,
}


// ExternalFinancialInstrumentIdentificationType1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ExternalFinancialInstrumentIdentificationType1Code {
	#[serde(rename = "ExternalFinancialInstrumentIdentificationType1Code")]
	pub external_financial_instrument_identification_type1_code: String,
}


// ExternalGarnishmentType1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ExternalGarnishmentType1Code {
	#[serde(rename = "ExternalGarnishmentType1Code")]
	pub external_garnishment_type1_code: String,
}


// ExternalLocalInstrument1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ExternalLocalInstrument1Code {
	#[serde(rename = "ExternalLocalInstrument1Code")]
	pub external_local_instrument1_code: String,
}


// ExternalOrganisationIdentification1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ExternalOrganisationIdentification1Code {
	#[serde(rename = "ExternalOrganisationIdentification1Code")]
	pub external_organisation_identification1_code: String,
}


// ExternalPersonIdentification1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ExternalPersonIdentification1Code {
	#[serde(rename = "ExternalPersonIdentification1Code")]
	pub external_person_identification1_code: String,
}


// ExternalProxyAccountType1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ExternalProxyAccountType1Code {
	#[serde(rename = "ExternalProxyAccountType1Code")]
	pub external_proxy_account_type1_code: String,
}


// ExternalPurpose1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ExternalPurpose1Code {
	#[serde(rename = "ExternalPurpose1Code")]
	pub external_purpose1_code: String,
}


// ExternalRePresentmentReason1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ExternalRePresentmentReason1Code {
	#[serde(rename = "ExternalRePresentmentReason1Code")]
	pub external_re_presentment_reason1_code: String,
}


// ExternalReportingSource1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ExternalReportingSource1Code {
	#[serde(rename = "ExternalReportingSource1Code")]
	pub external_reporting_source1_code: String,
}


// ExternalReturnReason1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ExternalReturnReason1Code {
	#[serde(rename = "ExternalReturnReason1Code")]
	pub external_return_reason1_code: String,
}


// ExternalTaxAmountType1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ExternalTaxAmountType1Code {
	#[serde(rename = "ExternalTaxAmountType1Code")]
	pub external_tax_amount_type1_code: String,
}


// ExternalTechnicalInputChannel1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ExternalTechnicalInputChannel1Code {
	#[serde(rename = "ExternalTechnicalInputChannel1Code")]
	pub external_technical_input_channel1_code: String,
}


// FinancialIdentificationSchemeName1Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct FinancialIdentificationSchemeName1Choice {
	#[serde(rename = "Cd")]
	pub cd: Option<String>,
	#[serde(rename = "Prtry")]
	pub prtry: Option<String>,
}


// FinancialInstitutionIdentification18 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct FinancialInstitutionIdentification18 {
	#[serde(rename = "BICFI")]
	pub bicfi: String,
	#[serde(rename = "ClrSysMmbId")]
	pub clr_sys_mmb_id: ClearingSystemMemberIdentification2,
	#[serde(rename = "LEI")]
	pub lei: String,
	#[serde(rename = "Nm")]
	pub nm: String,
	#[serde(rename = "PstlAdr")]
	pub pstl_adr: PostalAddress24,
	#[serde(rename = "Othr")]
	pub othr: GenericFinancialIdentification1,
}


// FinancialInstrumentQuantity1Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct FinancialInstrumentQuantity1Choice {
	#[serde(rename = "Unit")]
	pub unit: Option<f64>,
	#[serde(rename = "FaceAmt")]
	pub face_amt: Option<f64>,
	#[serde(rename = "AmtsdVal")]
	pub amtsd_val: Option<f64>,
}


// FromToAmountRange1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct FromToAmountRange1 {
	#[serde(rename = "FrAmt")]
	pub fr_amt: AmountRangeBoundary1,
	#[serde(rename = "ToAmt")]
	pub to_amt: AmountRangeBoundary1,
}


// Garnishment3 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Garnishment3 {
	#[serde(rename = "Tp")]
	pub tp: GarnishmentType1,
	#[serde(rename = "Grnshee")]
	pub grnshee: PartyIdentification135,
	#[serde(rename = "GrnshmtAdmstr")]
	pub grnshmt_admstr: PartyIdentification135,
	#[serde(rename = "RefNb")]
	pub ref_nb: String,
	#[serde(rename = "Dt")]
	pub dt: String,
	#[serde(rename = "RmtdAmt")]
	pub rmtd_amt: ActiveOrHistoricCurrencyAndAmount,
	#[serde(rename = "FmlyMdclInsrncInd")]
	pub fmly_mdcl_insrnc_ind: bool,
	#[serde(rename = "MplyeeTermntnInd")]
	pub mplyee_termntn_ind: bool,
}


// GarnishmentType1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct GarnishmentType1 {
	#[serde(rename = "CdOrPrtry")]
	pub cd_or_prtry: GarnishmentType1Choice,
	#[serde(rename = "Issr")]
	pub issr: String,
}


// GarnishmentType1Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct GarnishmentType1Choice {
	#[serde(rename = "Cd")]
	pub cd: Option<String>,
	#[serde(rename = "Prtry")]
	pub prtry: Option<String>,
}


// GenericAccountIdentification1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct GenericAccountIdentification1 {
	#[serde(rename = "Id")]
	pub id: String,
	#[serde(rename = "SchmeNm")]
	pub schme_nm: AccountSchemeName1Choice,
	#[serde(rename = "Issr")]
	pub issr: String,
}


// GenericFinancialIdentification1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct GenericFinancialIdentification1 {
	#[serde(rename = "Id")]
	pub id: String,
	#[serde(rename = "SchmeNm")]
	pub schme_nm: FinancialIdentificationSchemeName1Choice,
	#[serde(rename = "Issr")]
	pub issr: String,
}


// GenericIdentification1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct GenericIdentification1 {
	#[serde(rename = "Id")]
	pub id: String,
	#[serde(rename = "SchmeNm")]
	pub schme_nm: String,
	#[serde(rename = "Issr")]
	pub issr: String,
}


// GenericIdentification3 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct GenericIdentification3 {
	#[serde(rename = "Id")]
	pub id: String,
	#[serde(rename = "Issr")]
	pub issr: String,
}


// GenericIdentification30 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct GenericIdentification30 {
	#[serde(rename = "Id")]
	pub id: String,
	#[serde(rename = "Issr")]
	pub issr: String,
	#[serde(rename = "SchmeNm")]
	pub schme_nm: String,
}


// GenericIdentification32 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct GenericIdentification32 {
	#[serde(rename = "Id")]
	pub id: String,
	#[serde(rename = "Tp")]
	pub tp: String,
	#[serde(rename = "Issr")]
	pub issr: String,
	#[serde(rename = "ShrtNm")]
	pub shrt_nm: String,
}


// GenericOrganisationIdentification1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct GenericOrganisationIdentification1 {
	#[serde(rename = "Id")]
	pub id: String,
	#[serde(rename = "SchmeNm")]
	pub schme_nm: OrganisationIdentificationSchemeName1Choice,
	#[serde(rename = "Issr")]
	pub issr: String,
}


// GenericPersonIdentification1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct GenericPersonIdentification1 {
	#[serde(rename = "Id")]
	pub id: String,
	#[serde(rename = "SchmeNm")]
	pub schme_nm: PersonIdentificationSchemeName1Choice,
	#[serde(rename = "Issr")]
	pub issr: String,
}


// GroupHeader81 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct GroupHeader81 {
	#[serde(rename = "MsgId")]
	pub msg_id: String,
	#[serde(rename = "CreDtTm")]
	pub cre_dt_tm: String,
	#[serde(rename = "MsgRcpt")]
	pub msg_rcpt: PartyIdentification135,
	#[serde(rename = "MsgPgntn")]
	pub msg_pgntn: Pagination1,
	#[serde(rename = "OrgnlBizQry")]
	pub orgnl_biz_qry: OriginalBusinessQuery1,
	#[serde(rename = "AddtlInf")]
	pub addtl_inf: String,
}


// IBAN2007Identifier ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct IBAN2007Identifier {
	#[serde(rename = "IBAN2007Identifier")]
	pub iban2007_identifier: String,
}


// ISINOct2015Identifier ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ISINOct2015Identifier {
	#[serde(rename = "ISINOct2015Identifier")]
	pub isin_oct2015_identifier: String,
}


// ISO2ALanguageCode ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ISO2ALanguageCode {
	#[serde(rename = "ISO2ALanguageCode")]
	pub iso2_a_language_code: String,
}


// ISODate ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ISODate {
	#[serde(rename = "ISODate")]
	pub iso_date: String,
}


// ISODateTime ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ISODateTime {
	#[serde(rename = "ISODateTime")]
	pub iso_date_time: String,
}


// ISOYearMonth ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ISOYearMonth {
	#[serde(rename = "ISOYearMonth")]
	pub iso_year_month: String,
}


// IdentificationSource3Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct IdentificationSource3Choice {
	#[serde(rename = "Cd")]
	pub cd: Option<String>,
	#[serde(rename = "Prtry")]
	pub prtry: Option<String>,
}


// ImpliedCurrencyAmountRange1Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ImpliedCurrencyAmountRange1Choice {
	#[serde(rename = "FrAmt")]
	pub fr_amt: Option<AmountRangeBoundary1>,
	#[serde(rename = "ToAmt")]
	pub to_amt: Option<AmountRangeBoundary1>,
	#[serde(rename = "FrToAmt")]
	pub fr_to_amt: Option<FromToAmountRange1>,
	#[serde(rename = "EQAmt")]
	pub eq_amt: Option<f64>,
	#[serde(rename = "NEQAmt")]
	pub neq_amt: Option<f64>,
}


// ImpliedCurrencyAndAmount ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ImpliedCurrencyAndAmount {
	#[serde(rename = "ImpliedCurrencyAndAmount")]
	pub implied_currency_and_amount: f64,
}


// InterestRecord2 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct InterestRecord2 {
	#[serde(rename = "Amt")]
	pub amt: ActiveOrHistoricCurrencyAndAmount,
	#[serde(rename = "CdtDbtInd")]
	pub cdt_dbt_ind: String,
	#[serde(rename = "Tp")]
	pub tp: InterestType1Choice,
	#[serde(rename = "Rate")]
	pub rate: Rate4,
	#[serde(rename = "FrToDt")]
	pub fr_to_dt: DateTimePeriod1,
	#[serde(rename = "Rsn")]
	pub rsn: String,
	#[serde(rename = "Tax")]
	pub tax: TaxCharges2,
}


// InterestType1Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct InterestType1Choice {
	#[serde(rename = "Cd")]
	pub cd: Option<String>,
	#[serde(rename = "Prtry")]
	pub prtry: Option<String>,
}


// InterestType1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct InterestType1Code {
	#[serde(rename = "InterestType1Code")]
	pub interest_type1_code: String,
}


// LEIIdentifier ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct LEIIdentifier {
	#[serde(rename = "LEIIdentifier")]
	pub lei_identifier: String,
}


// LocalInstrument2Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct LocalInstrument2Choice {
	#[serde(rename = "Cd")]
	pub cd: Option<String>,
	#[serde(rename = "Prtry")]
	pub prtry: Option<String>,
}


// Max1025Text ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Max1025Text {
	#[serde(rename = "Max1025Text")]
	pub max1025_text: String,
}


// Max105Text ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Max105Text {
	#[serde(rename = "Max105Text")]
	pub max105_text: String,
}


// Max128Text ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Max128Text {
	#[serde(rename = "Max128Text")]
	pub max128_text: String,
}


// Max140Text ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Max140Text {
	#[serde(rename = "Max140Text")]
	pub max140_text: String,
}


// Max15NumericText ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Max15NumericText {
	#[serde(rename = "Max15NumericText")]
	pub max15_numeric_text: String,
}


// Max15PlusSignedNumericText ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Max15PlusSignedNumericText {
	#[serde(rename = "Max15PlusSignedNumericText")]
	pub max15_plus_signed_numeric_text: String,
}


// Max16Text ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Max16Text {
	#[serde(rename = "Max16Text")]
	pub max16_text: String,
}


// Max2048Text ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Max2048Text {
	#[serde(rename = "Max2048Text")]
	pub max2048_text: String,
}


// Max34Text ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Max34Text {
	#[serde(rename = "Max34Text")]
	pub max34_text: String,
}


// Max350Text ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Max350Text {
	#[serde(rename = "Max350Text")]
	pub max350_text: String,
}


// Max35Text ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Max35Text {
	#[serde(rename = "Max35Text")]
	pub max35_text: String,
}


// Max3NumericText ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Max3NumericText {
	#[serde(rename = "Max3NumericText")]
	pub max3_numeric_text: String,
}


// Max4Text ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Max4Text {
	#[serde(rename = "Max4Text")]
	pub max4_text: String,
}


// Max500Text ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Max500Text {
	#[serde(rename = "Max500Text")]
	pub max500_text: String,
}


// Max5NumericText ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Max5NumericText {
	#[serde(rename = "Max5NumericText")]
	pub max5_numeric_text: String,
}


// Max70Text ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Max70Text {
	#[serde(rename = "Max70Text")]
	pub max70_text: String,
}


// MessageIdentification2 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct MessageIdentification2 {
	#[serde(rename = "MsgNmId")]
	pub msg_nm_id: String,
	#[serde(rename = "MsgId")]
	pub msg_id: String,
}


// Min2Max3NumericText ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Min2Max3NumericText {
	#[serde(rename = "Min2Max3NumericText")]
	pub min2_max3_numeric_text: String,
}


// Min3Max4NumericText ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Min3Max4NumericText {
	#[serde(rename = "Min3Max4NumericText")]
	pub min3_max4_numeric_text: String,
}


// Min8Max28NumericText ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Min8Max28NumericText {
	#[serde(rename = "Min8Max28NumericText")]
	pub min8_max28_numeric_text: String,
}


// NameAndAddress16 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct NameAndAddress16 {
	#[serde(rename = "Nm")]
	pub nm: String,
	#[serde(rename = "Adr")]
	pub adr: PostalAddress24,
}


// NamePrefix2Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct NamePrefix2Code {
	#[serde(rename = "NamePrefix2Code")]
	pub name_prefix2_code: String,
}


// NonNegativeDecimalNumber ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct NonNegativeDecimalNumber {
	#[serde(rename = "NonNegativeDecimalNumber")]
	pub non_negative_decimal_number: f64,
}


// Number ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Number {
	#[serde(rename = "Number")]
	pub number: f64,
}


// NumberAndSumOfTransactions1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct NumberAndSumOfTransactions1 {
	#[serde(rename = "NbOfNtries")]
	pub nb_of_ntries: String,
	#[serde(rename = "Sum")]
	pub sum: f64,
}


// NumberAndSumOfTransactions4 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct NumberAndSumOfTransactions4 {
	#[serde(rename = "NbOfNtries")]
	pub nb_of_ntries: String,
	#[serde(rename = "Sum")]
	pub sum: f64,
	#[serde(rename = "TtlNetNtry")]
	pub ttl_net_ntry: AmountAndDirection35,
}


// OnLineCapability1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct OnLineCapability1Code {
	#[serde(rename = "OnLineCapability1Code")]
	pub on_line_capability1_code: String,
}


// OrganisationIdentification29 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct OrganisationIdentification29 {
	#[serde(rename = "AnyBIC")]
	pub any_bic: String,
	#[serde(rename = "LEI")]
	pub lei: String,
	#[serde(rename = "Othr")]
	pub othr: Vec<GenericOrganisationIdentification1>,
}


// OrganisationIdentificationSchemeName1Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct OrganisationIdentificationSchemeName1Choice {
	#[serde(rename = "Cd")]
	pub cd: Option<String>,
	#[serde(rename = "Prtry")]
	pub prtry: Option<String>,
}


// OriginalAndCurrentQuantities1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct OriginalAndCurrentQuantities1 {
	#[serde(rename = "FaceAmt")]
	pub face_amt: f64,
	#[serde(rename = "AmtsdVal")]
	pub amtsd_val: f64,
}


// OriginalBusinessQuery1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct OriginalBusinessQuery1 {
	#[serde(rename = "MsgId")]
	pub msg_id: String,
	#[serde(rename = "MsgNmId")]
	pub msg_nm_id: String,
	#[serde(rename = "CreDtTm")]
	pub cre_dt_tm: String,
}


// OtherContact1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct OtherContact1 {
	#[serde(rename = "ChanlTp")]
	pub chanl_tp: String,
	#[serde(rename = "Id")]
	pub id: String,
}


// OtherIdentification1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct OtherIdentification1 {
	#[serde(rename = "Id")]
	pub id: String,
	#[serde(rename = "Sfx")]
	pub sfx: String,
	#[serde(rename = "Tp")]
	pub tp: IdentificationSource3Choice,
}


// POIComponentType1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct POIComponentType1Code {
	#[serde(rename = "POIComponentType1Code")]
	pub poi_component_type1_code: String,
}


// Pagination1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Pagination1 {
	#[serde(rename = "PgNb")]
	pub pg_nb: String,
	#[serde(rename = "LastPgInd")]
	pub last_pg_ind: bool,
}


// Party38Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Party38Choice {
	#[serde(rename = "OrgId")]
	pub org_id: Option<OrganisationIdentification29>,
	#[serde(rename = "PrvtId")]
	pub prvt_id: Option<PersonIdentification13>,
}


// Party40Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Party40Choice {
	#[serde(rename = "Pty")]
	pub pty: Option<PartyIdentification135>,
	#[serde(rename = "Agt")]
	pub agt: Option<BranchAndFinancialInstitutionIdentification6>,
}


// PartyIdentification135 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct PartyIdentification135 {
	#[serde(rename = "Nm")]
	pub nm: String,
	#[serde(rename = "PstlAdr")]
	pub pstl_adr: PostalAddress24,
	#[serde(rename = "Id")]
	pub id: Party38Choice,
	#[serde(rename = "CtryOfRes")]
	pub ctry_of_res: String,
	#[serde(rename = "CtctDtls")]
	pub ctct_dtls: Contact4,
}


// PartyType3Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct PartyType3Code {
	#[serde(rename = "PartyType3Code")]
	pub party_type3_code: String,
}


// PartyType4Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct PartyType4Code {
	#[serde(rename = "PartyType4Code")]
	pub party_type4_code: String,
}


// PaymentCard4 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct PaymentCard4 {
	#[serde(rename = "PlainCardData")]
	pub plain_card_data: PlainCardData1,
	#[serde(rename = "CardCtryCd")]
	pub card_ctry_cd: String,
	#[serde(rename = "CardBrnd")]
	pub card_brnd: GenericIdentification1,
	#[serde(rename = "AddtlCardData")]
	pub addtl_card_data: String,
}


// PaymentContext3 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct PaymentContext3 {
	#[serde(rename = "CardPres")]
	pub card_pres: bool,
	#[serde(rename = "CrdhldrPres")]
	pub crdhldr_pres: bool,
	#[serde(rename = "OnLineCntxt")]
	pub on_line_cntxt: bool,
	#[serde(rename = "AttndncCntxt")]
	pub attndnc_cntxt: String,
	#[serde(rename = "TxEnvt")]
	pub tx_envt: String,
	#[serde(rename = "TxChanl")]
	pub tx_chanl: String,
	#[serde(rename = "AttndntMsgCpbl")]
	pub attndnt_msg_cpbl: bool,
	#[serde(rename = "AttndntLang")]
	pub attndnt_lang: String,
	#[serde(rename = "CardDataNtryMd")]
	pub card_data_ntry_md: String,
	#[serde(rename = "FllbckInd")]
	pub fllbck_ind: bool,
	#[serde(rename = "AuthntcnMtd")]
	pub authntcn_mtd: CardholderAuthentication2,
}


// PaymentReturnReason5 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct PaymentReturnReason5 {
	#[serde(rename = "OrgnlBkTxCd")]
	pub orgnl_bk_tx_cd: BankTransactionCodeStructure4,
	#[serde(rename = "Orgtr")]
	pub orgtr: PartyIdentification135,
	#[serde(rename = "Rsn")]
	pub rsn: ReturnReason5Choice,
	#[serde(rename = "AddtlInf")]
	pub addtl_inf: Vec<String>,
}


// PercentageRate ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct PercentageRate {
	#[serde(rename = "PercentageRate")]
	pub percentage_rate: f64,
}


// PersonIdentification13 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct PersonIdentification13 {
	#[serde(rename = "DtAndPlcOfBirth")]
	pub dt_and_plc_of_birth: DateAndPlaceOfBirth1,
	#[serde(rename = "Othr")]
	pub othr: Vec<GenericPersonIdentification1>,
}


// PersonIdentificationSchemeName1Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct PersonIdentificationSchemeName1Choice {
	#[serde(rename = "Cd")]
	pub cd: Option<String>,
	#[serde(rename = "Prtry")]
	pub prtry: Option<String>,
}


// PhoneNumber ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct PhoneNumber {
	#[serde(rename = "PhoneNumber")]
	pub phone_number: String,
}


// PlainCardData1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct PlainCardData1 {
	#[serde(rename = "PAN")]
	pub pan: String,
	#[serde(rename = "CardSeqNb")]
	pub card_seq_nb: String,
	#[serde(rename = "FctvDt")]
	pub fctv_dt: String,
	#[serde(rename = "XpryDt")]
	pub xpry_dt: String,
	#[serde(rename = "SvcCd")]
	pub svc_cd: String,
	#[serde(rename = "TrckData")]
	pub trck_data: Vec<TrackData1>,
	#[serde(rename = "CardSctyCd")]
	pub card_scty_cd: CardSecurityInformation1,
}


// PointOfInteraction1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct PointOfInteraction1 {
	#[serde(rename = "Id")]
	pub id: GenericIdentification32,
	#[serde(rename = "SysNm")]
	pub sys_nm: String,
	#[serde(rename = "GrpId")]
	pub grp_id: String,
	#[serde(rename = "Cpblties")]
	pub cpblties: PointOfInteractionCapabilities1,
	#[serde(rename = "Cmpnt")]
	pub cmpnt: Vec<PointOfInteractionComponent1>,
}


// PointOfInteractionCapabilities1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct PointOfInteractionCapabilities1 {
	#[serde(rename = "CardRdngCpblties")]
	pub card_rdng_cpblties: Vec<String>,
	#[serde(rename = "CrdhldrVrfctnCpblties")]
	pub crdhldr_vrfctn_cpblties: Vec<String>,
	#[serde(rename = "OnLineCpblties")]
	pub on_line_cpblties: String,
	#[serde(rename = "DispCpblties")]
	pub disp_cpblties: Vec<DisplayCapabilities1>,
	#[serde(rename = "PrtLineWidth")]
	pub prt_line_width: String,
}


// PointOfInteractionComponent1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct PointOfInteractionComponent1 {
	#[serde(rename = "POICmpntTp")]
	pub poi_cmpnt_tp: String,
	#[serde(rename = "ManfctrId")]
	pub manfctr_id: String,
	#[serde(rename = "Mdl")]
	pub mdl: String,
	#[serde(rename = "VrsnNb")]
	pub vrsn_nb: String,
	#[serde(rename = "SrlNb")]
	pub srl_nb: String,
	#[serde(rename = "ApprvlNb")]
	pub apprvl_nb: Vec<String>,
}


// PostalAddress24 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct PostalAddress24 {
	#[serde(rename = "AdrTp")]
	pub adr_tp: AddressType3Choice,
	#[serde(rename = "Dept")]
	pub dept: String,
	#[serde(rename = "SubDept")]
	pub sub_dept: String,
	#[serde(rename = "StrtNm")]
	pub strt_nm: String,
	#[serde(rename = "BldgNb")]
	pub bldg_nb: String,
	#[serde(rename = "BldgNm")]
	pub bldg_nm: String,
	#[serde(rename = "Flr")]
	pub flr: String,
	#[serde(rename = "PstBx")]
	pub pst_bx: String,
	#[serde(rename = "Room")]
	pub room: String,
	#[serde(rename = "PstCd")]
	pub pst_cd: String,
	#[serde(rename = "TwnNm")]
	pub twn_nm: String,
	#[serde(rename = "TwnLctnNm")]
	pub twn_lctn_nm: String,
	#[serde(rename = "DstrctNm")]
	pub dstrct_nm: String,
	#[serde(rename = "CtrySubDvsn")]
	pub ctry_sub_dvsn: String,
	#[serde(rename = "Ctry")]
	pub ctry: String,
	#[serde(rename = "AdrLine")]
	pub adr_line: Vec<String>,
}


// PreferredContactMethod1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct PreferredContactMethod1Code {
	#[serde(rename = "PreferredContactMethod1Code")]
	pub preferred_contact_method1_code: String,
}


// Price7 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Price7 {
	#[serde(rename = "Tp")]
	pub tp: YieldedOrValueType1Choice,
	#[serde(rename = "Val")]
	pub val: PriceRateOrAmount3Choice,
}


// PriceRateOrAmount3Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct PriceRateOrAmount3Choice {
	#[serde(rename = "Rate")]
	pub rate: Option<f64>,
	#[serde(rename = "Amt")]
	pub amt: Option<ActiveOrHistoricCurrencyAnd13DecimalAmount>,
}


// PriceValueType1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct PriceValueType1Code {
	#[serde(rename = "PriceValueType1Code")]
	pub price_value_type1_code: String,
}


// Product2 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Product2 {
	#[serde(rename = "PdctCd")]
	pub pdct_cd: String,
	#[serde(rename = "UnitOfMeasr")]
	pub unit_of_measr: String,
	#[serde(rename = "PdctQty")]
	pub pdct_qty: f64,
	#[serde(rename = "UnitPric")]
	pub unit_pric: f64,
	#[serde(rename = "PdctAmt")]
	pub pdct_amt: f64,
	#[serde(rename = "TaxTp")]
	pub tax_tp: String,
	#[serde(rename = "AddtlPdctInf")]
	pub addtl_pdct_inf: String,
}


// ProprietaryAgent4 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ProprietaryAgent4 {
	#[serde(rename = "Tp")]
	pub tp: String,
	#[serde(rename = "Agt")]
	pub agt: BranchAndFinancialInstitutionIdentification6,
}


// ProprietaryBankTransactionCodeStructure1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ProprietaryBankTransactionCodeStructure1 {
	#[serde(rename = "Cd")]
	pub cd: String,
	#[serde(rename = "Issr")]
	pub issr: String,
}


// ProprietaryDate3 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ProprietaryDate3 {
	#[serde(rename = "Tp")]
	pub tp: String,
	#[serde(rename = "Dt")]
	pub dt: DateAndDateTime2Choice,
}


// ProprietaryParty5 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ProprietaryParty5 {
	#[serde(rename = "Tp")]
	pub tp: String,
	#[serde(rename = "Pty")]
	pub pty: Party40Choice,
}


// ProprietaryPrice2 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ProprietaryPrice2 {
	#[serde(rename = "Tp")]
	pub tp: String,
	#[serde(rename = "Pric")]
	pub pric: ActiveOrHistoricCurrencyAndAmount,
}


// ProprietaryQuantity1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ProprietaryQuantity1 {
	#[serde(rename = "Tp")]
	pub tp: String,
	#[serde(rename = "Qty")]
	pub qty: String,
}


// ProprietaryReference1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ProprietaryReference1 {
	#[serde(rename = "Tp")]
	pub tp: String,
	#[serde(rename = "Ref")]
	pub ref_attr: String,
}


// ProxyAccountIdentification1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ProxyAccountIdentification1 {
	#[serde(rename = "Tp")]
	pub tp: ProxyAccountType1Choice,
	#[serde(rename = "Id")]
	pub id: String,
}


// ProxyAccountType1Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ProxyAccountType1Choice {
	#[serde(rename = "Cd")]
	pub cd: Option<String>,
	#[serde(rename = "Prtry")]
	pub prtry: Option<String>,
}


// Purpose2Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Purpose2Choice {
	#[serde(rename = "Cd")]
	pub cd: Option<String>,
	#[serde(rename = "Prtry")]
	pub prtry: Option<String>,
}


// Rate4 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Rate4 {
	#[serde(rename = "Tp")]
	pub tp: RateType4Choice,
	#[serde(rename = "VldtyRg")]
	pub vldty_rg: ActiveOrHistoricCurrencyAndAmountRange2,
}


// RateType4Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct RateType4Choice {
	#[serde(rename = "Pctg")]
	pub pctg: Option<f64>,
	#[serde(rename = "Othr")]
	pub othr: Option<String>,
}


// ReferredDocumentInformation7 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ReferredDocumentInformation7 {
	#[serde(rename = "Tp")]
	pub tp: ReferredDocumentType4,
	#[serde(rename = "Nb")]
	pub nb: String,
	#[serde(rename = "RltdDt")]
	pub rltd_dt: String,
	#[serde(rename = "LineDtls")]
	pub line_dtls: Vec<DocumentLineInformation1>,
}


// ReferredDocumentType3Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ReferredDocumentType3Choice {
	#[serde(rename = "Cd")]
	pub cd: Option<String>,
	#[serde(rename = "Prtry")]
	pub prtry: Option<String>,
}


// ReferredDocumentType4 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ReferredDocumentType4 {
	#[serde(rename = "CdOrPrtry")]
	pub cd_or_prtry: ReferredDocumentType3Choice,
	#[serde(rename = "Issr")]
	pub issr: String,
}


// RemittanceAmount2 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct RemittanceAmount2 {
	#[serde(rename = "DuePyblAmt")]
	pub due_pybl_amt: ActiveOrHistoricCurrencyAndAmount,
	#[serde(rename = "DscntApldAmt")]
	pub dscnt_apld_amt: Vec<DiscountAmountAndType1>,
	#[serde(rename = "CdtNoteAmt")]
	pub cdt_note_amt: ActiveOrHistoricCurrencyAndAmount,
	#[serde(rename = "TaxAmt")]
	pub tax_amt: Vec<TaxAmountAndType1>,
	#[serde(rename = "AdjstmntAmtAndRsn")]
	pub adjstmnt_amt_and_rsn: Vec<DocumentAdjustment1>,
	#[serde(rename = "RmtdAmt")]
	pub rmtd_amt: ActiveOrHistoricCurrencyAndAmount,
}


// RemittanceAmount3 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct RemittanceAmount3 {
	#[serde(rename = "DuePyblAmt")]
	pub due_pybl_amt: ActiveOrHistoricCurrencyAndAmount,
	#[serde(rename = "DscntApldAmt")]
	pub dscnt_apld_amt: Vec<DiscountAmountAndType1>,
	#[serde(rename = "CdtNoteAmt")]
	pub cdt_note_amt: ActiveOrHistoricCurrencyAndAmount,
	#[serde(rename = "TaxAmt")]
	pub tax_amt: Vec<TaxAmountAndType1>,
	#[serde(rename = "AdjstmntAmtAndRsn")]
	pub adjstmnt_amt_and_rsn: Vec<DocumentAdjustment1>,
	#[serde(rename = "RmtdAmt")]
	pub rmtd_amt: ActiveOrHistoricCurrencyAndAmount,
}


// RemittanceInformation16 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct RemittanceInformation16 {
	#[serde(rename = "Ustrd")]
	pub ustrd: Vec<String>,
	#[serde(rename = "Strd")]
	pub strd: Vec<StructuredRemittanceInformation16>,
}


// RemittanceLocation7 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct RemittanceLocation7 {
	#[serde(rename = "RmtId")]
	pub rmt_id: String,
	#[serde(rename = "RmtLctnDtls")]
	pub rmt_lctn_dtls: Vec<RemittanceLocationData1>,
}


// RemittanceLocationData1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct RemittanceLocationData1 {
	#[serde(rename = "Mtd")]
	pub mtd: String,
	#[serde(rename = "ElctrncAdr")]
	pub elctrnc_adr: String,
	#[serde(rename = "PstlAdr")]
	pub pstl_adr: NameAndAddress16,
}


// RemittanceLocationMethod2Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct RemittanceLocationMethod2Code {
	#[serde(rename = "RemittanceLocationMethod2Code")]
	pub remittance_location_method2_code: String,
}


// ReportEntry10 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ReportEntry10 {
	#[serde(rename = "NtryRef")]
	pub ntry_ref: String,
	#[serde(rename = "Amt")]
	pub amt: ActiveOrHistoricCurrencyAndAmount,
	#[serde(rename = "CdtDbtInd")]
	pub cdt_dbt_ind: String,
	#[serde(rename = "RvslInd")]
	pub rvsl_ind: bool,
	#[serde(rename = "Sts")]
	pub sts: EntryStatus1Choice,
	#[serde(rename = "BookgDt")]
	pub bookg_dt: DateAndDateTime2Choice,
	#[serde(rename = "ValDt")]
	pub val_dt: DateAndDateTime2Choice,
	#[serde(rename = "AcctSvcrRef")]
	pub acct_svcr_ref: String,
	#[serde(rename = "Avlbty")]
	pub avlbty: Vec<CashAvailability1>,
	#[serde(rename = "BkTxCd")]
	pub bk_tx_cd: BankTransactionCodeStructure4,
	#[serde(rename = "ComssnWvrInd")]
	pub comssn_wvr_ind: bool,
	#[serde(rename = "AddtlInfInd")]
	pub addtl_inf_ind: MessageIdentification2,
	#[serde(rename = "AmtDtls")]
	pub amt_dtls: AmountAndCurrencyExchange3,
	#[serde(rename = "Chrgs")]
	pub chrgs: Charges6,
	#[serde(rename = "TechInptChanl")]
	pub tech_inpt_chanl: TechnicalInputChannel1Choice,
	#[serde(rename = "Intrst")]
	pub intrst: TransactionInterest4,
	#[serde(rename = "CardTx")]
	pub card_tx: CardEntry4,
	#[serde(rename = "NtryDtls")]
	pub ntry_dtls: Vec<EntryDetails9>,
	#[serde(rename = "AddtlNtryInf")]
	pub addtl_ntry_inf: String,
}


// ReportingSource1Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ReportingSource1Choice {
	#[serde(rename = "Cd")]
	pub cd: Option<String>,
	#[serde(rename = "Prtry")]
	pub prtry: Option<String>,
}


// ReturnReason5Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ReturnReason5Choice {
	#[serde(rename = "Cd")]
	pub cd: Option<String>,
	#[serde(rename = "Prtry")]
	pub prtry: Option<String>,
}


// SecuritiesAccount19 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct SecuritiesAccount19 {
	#[serde(rename = "Id")]
	pub id: String,
	#[serde(rename = "Tp")]
	pub tp: GenericIdentification30,
	#[serde(rename = "Nm")]
	pub nm: String,
}


// SecurityIdentification19 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct SecurityIdentification19 {
	#[serde(rename = "ISIN")]
	pub isin: String,
	#[serde(rename = "OthrId")]
	pub othr_id: Vec<OtherIdentification1>,
	#[serde(rename = "Desc")]
	pub desc: String,
}


// SequenceRange1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct SequenceRange1 {
	#[serde(rename = "FrSeq")]
	pub fr_seq: String,
	#[serde(rename = "ToSeq")]
	pub to_seq: String,
}


// SequenceRange1Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct SequenceRange1Choice {
	#[serde(rename = "FrSeq")]
	pub fr_seq: Option<String>,
	#[serde(rename = "ToSeq")]
	pub to_seq: Option<String>,
	#[serde(rename = "FrToSeq")]
	pub fr_to_seq: Vec<SequenceRange1>,
	#[serde(rename = "EQSeq")]
	pub eq_seq: Vec<String>,
	#[serde(rename = "NEQSeq")]
	pub neq_seq: Vec<String>,
}


// StructuredRemittanceInformation16 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct StructuredRemittanceInformation16 {
	#[serde(rename = "RfrdDocInf")]
	pub rfrd_doc_inf: Vec<ReferredDocumentInformation7>,
	#[serde(rename = "RfrdDocAmt")]
	pub rfrd_doc_amt: RemittanceAmount2,
	#[serde(rename = "CdtrRefInf")]
	pub cdtr_ref_inf: CreditorReferenceInformation2,
	#[serde(rename = "Invcr")]
	pub invcr: PartyIdentification135,
	#[serde(rename = "Invcee")]
	pub invcee: PartyIdentification135,
	#[serde(rename = "TaxRmt")]
	pub tax_rmt: TaxInformation7,
	#[serde(rename = "GrnshmtRmt")]
	pub grnshmt_rmt: Garnishment3,
	#[serde(rename = "AddtlRmtInf")]
	pub addtl_rmt_inf: Vec<String>,
}


// SupplementaryData1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct SupplementaryData1 {
	#[serde(rename = "PlcAndNm")]
	pub plc_and_nm: String,
	#[serde(rename = "Envlp")]
	pub envlp: SupplementaryDataEnvelope1,
}


// SupplementaryDataEnvelope1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct SupplementaryDataEnvelope1 {
}


// TaxAmount2 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TaxAmount2 {
	#[serde(rename = "Rate")]
	pub rate: f64,
	#[serde(rename = "TaxblBaseAmt")]
	pub taxbl_base_amt: ActiveOrHistoricCurrencyAndAmount,
	#[serde(rename = "TtlAmt")]
	pub ttl_amt: ActiveOrHistoricCurrencyAndAmount,
	#[serde(rename = "Dtls")]
	pub dtls: Vec<TaxRecordDetails2>,
}


// TaxAmountAndType1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TaxAmountAndType1 {
	#[serde(rename = "Tp")]
	pub tp: TaxAmountType1Choice,
	#[serde(rename = "Amt")]
	pub amt: ActiveOrHistoricCurrencyAndAmount,
}


// TaxAmountType1Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TaxAmountType1Choice {
	#[serde(rename = "Cd")]
	pub cd: Option<String>,
	#[serde(rename = "Prtry")]
	pub prtry: Option<String>,
}


// TaxAuthorisation1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TaxAuthorisation1 {
	#[serde(rename = "Titl")]
	pub titl: String,
	#[serde(rename = "Nm")]
	pub nm: String,
}


// TaxCharges2 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TaxCharges2 {
	#[serde(rename = "Id")]
	pub id: String,
	#[serde(rename = "Rate")]
	pub rate: f64,
	#[serde(rename = "Amt")]
	pub amt: ActiveOrHistoricCurrencyAndAmount,
}


// TaxInformation7 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TaxInformation7 {
	#[serde(rename = "Cdtr")]
	pub cdtr: TaxParty1,
	#[serde(rename = "Dbtr")]
	pub dbtr: TaxParty2,
	#[serde(rename = "UltmtDbtr")]
	pub ultmt_dbtr: TaxParty2,
	#[serde(rename = "AdmstnZone")]
	pub admstn_zone: String,
	#[serde(rename = "RefNb")]
	pub ref_nb: String,
	#[serde(rename = "Mtd")]
	pub mtd: String,
	#[serde(rename = "TtlTaxblBaseAmt")]
	pub ttl_taxbl_base_amt: ActiveOrHistoricCurrencyAndAmount,
	#[serde(rename = "TtlTaxAmt")]
	pub ttl_tax_amt: ActiveOrHistoricCurrencyAndAmount,
	#[serde(rename = "Dt")]
	pub dt: String,
	#[serde(rename = "SeqNb")]
	pub seq_nb: f64,
	#[serde(rename = "Rcrd")]
	pub rcrd: Vec<TaxRecord2>,
}


// TaxInformation8 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TaxInformation8 {
	#[serde(rename = "Cdtr")]
	pub cdtr: TaxParty1,
	#[serde(rename = "Dbtr")]
	pub dbtr: TaxParty2,
	#[serde(rename = "AdmstnZone")]
	pub admstn_zone: String,
	#[serde(rename = "RefNb")]
	pub ref_nb: String,
	#[serde(rename = "Mtd")]
	pub mtd: String,
	#[serde(rename = "TtlTaxblBaseAmt")]
	pub ttl_taxbl_base_amt: ActiveOrHistoricCurrencyAndAmount,
	#[serde(rename = "TtlTaxAmt")]
	pub ttl_tax_amt: ActiveOrHistoricCurrencyAndAmount,
	#[serde(rename = "Dt")]
	pub dt: String,
	#[serde(rename = "SeqNb")]
	pub seq_nb: f64,
	#[serde(rename = "Rcrd")]
	pub rcrd: Vec<TaxRecord2>,
}


// TaxParty1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TaxParty1 {
	#[serde(rename = "TaxId")]
	pub tax_id: String,
	#[serde(rename = "RegnId")]
	pub regn_id: String,
	#[serde(rename = "TaxTp")]
	pub tax_tp: String,
}


// TaxParty2 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TaxParty2 {
	#[serde(rename = "TaxId")]
	pub tax_id: String,
	#[serde(rename = "RegnId")]
	pub regn_id: String,
	#[serde(rename = "TaxTp")]
	pub tax_tp: String,
	#[serde(rename = "Authstn")]
	pub authstn: TaxAuthorisation1,
}


// TaxPeriod2 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TaxPeriod2 {
	#[serde(rename = "Yr")]
	pub yr: String,
	#[serde(rename = "Tp")]
	pub tp: String,
	#[serde(rename = "FrToDt")]
	pub fr_to_dt: DatePeriod2,
}


// TaxRecord2 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TaxRecord2 {
	#[serde(rename = "Tp")]
	pub tp: String,
	#[serde(rename = "Ctgy")]
	pub ctgy: String,
	#[serde(rename = "CtgyDtls")]
	pub ctgy_dtls: String,
	#[serde(rename = "DbtrSts")]
	pub dbtr_sts: String,
	#[serde(rename = "CertId")]
	pub cert_id: String,
	#[serde(rename = "FrmsCd")]
	pub frms_cd: String,
	#[serde(rename = "Prd")]
	pub prd: TaxPeriod2,
	#[serde(rename = "TaxAmt")]
	pub tax_amt: TaxAmount2,
	#[serde(rename = "AddtlInf")]
	pub addtl_inf: String,
}


// TaxRecordDetails2 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TaxRecordDetails2 {
	#[serde(rename = "Prd")]
	pub prd: TaxPeriod2,
	#[serde(rename = "Amt")]
	pub amt: ActiveOrHistoricCurrencyAndAmount,
}


// TaxRecordPeriod1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TaxRecordPeriod1Code {
	#[serde(rename = "TaxRecordPeriod1Code")]
	pub tax_record_period1_code: String,
}


// TechnicalInputChannel1Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TechnicalInputChannel1Choice {
	#[serde(rename = "Cd")]
	pub cd: Option<String>,
	#[serde(rename = "Prtry")]
	pub prtry: Option<String>,
}


// TotalTransactions6 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TotalTransactions6 {
	#[serde(rename = "TtlNtries")]
	pub ttl_ntries: NumberAndSumOfTransactions4,
	#[serde(rename = "TtlCdtNtries")]
	pub ttl_cdt_ntries: NumberAndSumOfTransactions1,
	#[serde(rename = "TtlDbtNtries")]
	pub ttl_dbt_ntries: NumberAndSumOfTransactions1,
	#[serde(rename = "TtlNtriesPerBkTxCd")]
	pub ttl_ntries_per_bk_tx_cd: Vec<TotalsPerBankTransactionCode5>,
}


// TotalsPerBankTransactionCode5 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TotalsPerBankTransactionCode5 {
	#[serde(rename = "NbOfNtries")]
	pub nb_of_ntries: String,
	#[serde(rename = "Sum")]
	pub sum: f64,
	#[serde(rename = "TtlNetNtry")]
	pub ttl_net_ntry: AmountAndDirection35,
	#[serde(rename = "CdtNtries")]
	pub cdt_ntries: NumberAndSumOfTransactions1,
	#[serde(rename = "DbtNtries")]
	pub dbt_ntries: NumberAndSumOfTransactions1,
	#[serde(rename = "FcstInd")]
	pub fcst_ind: bool,
	#[serde(rename = "BkTxCd")]
	pub bk_tx_cd: BankTransactionCodeStructure4,
	#[serde(rename = "Avlbty")]
	pub avlbty: Vec<CashAvailability1>,
	#[serde(rename = "Dt")]
	pub dt: DateAndDateTime2Choice,
}


// TrackData1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TrackData1 {
	#[serde(rename = "TrckNb")]
	pub trck_nb: String,
	#[serde(rename = "TrckVal")]
	pub trck_val: String,
}


// TransactionAgents5 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TransactionAgents5 {
	#[serde(rename = "InstgAgt")]
	pub instg_agt: BranchAndFinancialInstitutionIdentification6,
	#[serde(rename = "InstdAgt")]
	pub instd_agt: BranchAndFinancialInstitutionIdentification6,
	#[serde(rename = "DbtrAgt")]
	pub dbtr_agt: BranchAndFinancialInstitutionIdentification6,
	#[serde(rename = "CdtrAgt")]
	pub cdtr_agt: BranchAndFinancialInstitutionIdentification6,
	#[serde(rename = "IntrmyAgt1")]
	pub intrmy_agt1: BranchAndFinancialInstitutionIdentification6,
	#[serde(rename = "IntrmyAgt2")]
	pub intrmy_agt2: BranchAndFinancialInstitutionIdentification6,
	#[serde(rename = "IntrmyAgt3")]
	pub intrmy_agt3: BranchAndFinancialInstitutionIdentification6,
	#[serde(rename = "RcvgAgt")]
	pub rcvg_agt: BranchAndFinancialInstitutionIdentification6,
	#[serde(rename = "DlvrgAgt")]
	pub dlvrg_agt: BranchAndFinancialInstitutionIdentification6,
	#[serde(rename = "IssgAgt")]
	pub issg_agt: BranchAndFinancialInstitutionIdentification6,
	#[serde(rename = "SttlmPlc")]
	pub sttlm_plc: BranchAndFinancialInstitutionIdentification6,
	#[serde(rename = "Prtry")]
	pub prtry: Vec<ProprietaryAgent4>,
}


// TransactionChannel1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TransactionChannel1Code {
	#[serde(rename = "TransactionChannel1Code")]
	pub transaction_channel1_code: String,
}


// TransactionDates3 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TransactionDates3 {
	#[serde(rename = "AccptncDtTm")]
	pub accptnc_dt_tm: String,
	#[serde(rename = "TradActvtyCtrctlSttlmDt")]
	pub trad_actvty_ctrctl_sttlm_dt: String,
	#[serde(rename = "TradDt")]
	pub trad_dt: String,
	#[serde(rename = "IntrBkSttlmDt")]
	pub intr_bk_sttlm_dt: String,
	#[serde(rename = "StartDt")]
	pub start_dt: String,
	#[serde(rename = "EndDt")]
	pub end_dt: String,
	#[serde(rename = "TxDtTm")]
	pub tx_dt_tm: String,
	#[serde(rename = "Prtry")]
	pub prtry: Vec<ProprietaryDate3>,
}


// TransactionEnvironment1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TransactionEnvironment1Code {
	#[serde(rename = "TransactionEnvironment1Code")]
	pub transaction_environment1_code: String,
}


// TransactionIdentifier1 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TransactionIdentifier1 {
	#[serde(rename = "TxDtTm")]
	pub tx_dt_tm: String,
	#[serde(rename = "TxRef")]
	pub tx_ref: String,
}


// TransactionInterest4 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TransactionInterest4 {
	#[serde(rename = "TtlIntrstAndTaxAmt")]
	pub ttl_intrst_and_tax_amt: ActiveOrHistoricCurrencyAndAmount,
	#[serde(rename = "Rcrd")]
	pub rcrd: Vec<InterestRecord2>,
}


// TransactionParties6 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TransactionParties6 {
	#[serde(rename = "InitgPty")]
	pub initg_pty: Party40Choice,
	#[serde(rename = "Dbtr")]
	pub dbtr: Party40Choice,
	#[serde(rename = "DbtrAcct")]
	pub dbtr_acct: CashAccount38,
	#[serde(rename = "UltmtDbtr")]
	pub ultmt_dbtr: Party40Choice,
	#[serde(rename = "Cdtr")]
	pub cdtr: Party40Choice,
	#[serde(rename = "CdtrAcct")]
	pub cdtr_acct: CashAccount38,
	#[serde(rename = "UltmtCdtr")]
	pub ultmt_cdtr: Party40Choice,
	#[serde(rename = "TradgPty")]
	pub tradg_pty: Party40Choice,
	#[serde(rename = "Prtry")]
	pub prtry: Vec<ProprietaryParty5>,
}


// TransactionPrice4Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TransactionPrice4Choice {
	#[serde(rename = "DealPric")]
	pub deal_pric: Option<Price7>,
	#[serde(rename = "Prtry")]
	pub prtry: Vec<ProprietaryPrice2>,
}


// TransactionQuantities3Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TransactionQuantities3Choice {
	#[serde(rename = "Qty")]
	pub qty: Option<FinancialInstrumentQuantity1Choice>,
	#[serde(rename = "OrgnlAndCurFaceAmt")]
	pub orgnl_and_cur_face_amt: Option<OriginalAndCurrentQuantities1>,
	#[serde(rename = "Prtry")]
	pub prtry: Option<ProprietaryQuantity1>,
}


// TransactionReferences6 ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TransactionReferences6 {
	#[serde(rename = "MsgId")]
	pub msg_id: String,
	#[serde(rename = "AcctSvcrRef")]
	pub acct_svcr_ref: String,
	#[serde(rename = "PmtInfId")]
	pub pmt_inf_id: String,
	#[serde(rename = "InstrId")]
	pub instr_id: String,
	#[serde(rename = "EndToEndId")]
	pub end_to_end_id: String,
	#[serde(rename = "UETR")]
	pub uetr: String,
	#[serde(rename = "TxId")]
	pub tx_id: String,
	#[serde(rename = "MndtId")]
	pub mndt_id: String,
	#[serde(rename = "ChqNb")]
	pub chq_nb: String,
	#[serde(rename = "ClrSysRef")]
	pub clr_sys_ref: String,
	#[serde(rename = "AcctOwnrTxId")]
	pub acct_ownr_tx_id: String,
	#[serde(rename = "AcctSvcrTxId")]
	pub acct_svcr_tx_id: String,
	#[serde(rename = "MktInfrstrctrTxId")]
	pub mkt_infrstrctr_tx_id: String,
	#[serde(rename = "PrcgId")]
	pub prcg_id: String,
	#[serde(rename = "Prtry")]
	pub prtry: Vec<ProprietaryReference1>,
}


// TrueFalseIndicator ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct TrueFalseIndicator {
	#[serde(rename = "TrueFalseIndicator")]
	pub true_false_indicator: bool,
}


// UUIDv4Identifier ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct UUIDv4Identifier {
	#[serde(rename = "UUIDv4Identifier")]
	pub uui_dv4_identifier: String,
}


// UnitOfMeasure1Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct UnitOfMeasure1Code {
	#[serde(rename = "UnitOfMeasure1Code")]
	pub unit_of_measure1_code: String,
}


// UserInterface2Code ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct UserInterface2Code {
	#[serde(rename = "UserInterface2Code")]
	pub user_interface2_code: String,
}


// YesNoIndicator ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct YesNoIndicator {
	#[serde(rename = "YesNoIndicator")]
	pub yes_no_indicator: bool,
}


// YieldedOrValueType1Choice ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct YieldedOrValueType1Choice {
	#[serde(rename = "Yldd")]
	pub yldd: Option<bool>,
	#[serde(rename = "ValTp")]
	pub val_tp: Option<String>,
}
