// Code generated by xgen. DO NOT EDIT.

use serde::{Deserialize, Serialize};


// FedNowParticipantFile1 is This is the participant profile of the FedNow participant and contains the participant's identification, name and the FedNow services the participant has enrolled for.
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct FedNowParticipantFile1 {
	#[serde(rename = "BizDay")]
	pub biz_day: String,
	#[serde(rename = "PtcptPrfl")]
	pub ptcpt_prfl: Vec<FedNowParticipantProfile1>,
}


// FedNowParticipantProfile1 is This specifies the FedNow services the FedNow participant has enrolled for.
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct FedNowParticipantProfile1 {
	#[serde(rename = "Id")]
	pub id: String,
	#[serde(rename = "Nm")]
	pub nm: String,
	#[serde(rename = "Svcs")]
	pub svcs: Vec<String>,
}


// ISODate is A particular point in the progression of time in a calendar year expressed in the YYYY-MM-DD format. This representation is defined in "XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004" which is aligned with ISO 8601.
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ISODate {
	#[serde(rename = "ISODate")]
	pub iso_date: String,
}


// Max140Text is Specifies a character string with a maximum length of 140 characters.
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Max140Text {
	#[serde(rename = "Max140Text")]
	pub max140_text: String,
}


// RoutingNumberFRS1 is This is a routing number used by the Service participant in connection with the message.

//                 

//                 Note: This may be a master account routing number or a subaccount routing number.
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct RoutingNumberFRS1 {
	#[serde(rename = "RoutingNumber_FRS_1")]
	pub routing_number_frs_1: String,
}


// ServicesFedNow1 is This indicates a FedNow participant is enabled to receive request for payment messages.
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ServicesFedNow1 {
	#[serde(rename = "Services_FedNow_1")]
	pub services_fed_now_1: String,
}


// Admi998SuplDataV01 is This is the FedNow participant file and contains the FedNow Service funds-transfer business day and the FedNow participants with their FedNow Service profile.
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Admi998SuplDataV01 {
	#[serde(rename = "PtcptFile")]
	pub ptcpt_file: FedNowParticipantFile1,
}
