name: Publish Crate

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Extract crate version from Cargo.toml
      id: version
      run: |
        VERSION=$(grep '^version =' Cargo.toml | head -n 1 | cut -d '"' -f 2)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Tag the repository with the crate version
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag -a "v${{ env.VERSION }}" -m "Version ${{ env.VERSION }} release"
        git push origin "v${{ env.VERSION }}"
